apiVersion: apps/v1
kind: Deployment
metadata:
  name: assets-server
spec:
  selector:
    matchLabels:
      app: assets-server
  template:
    metadata:
      labels:
        app: assets-server
    spec:
      containers:
      - name: assets-server
        image: docker.io/library/nginx-assets-server:latest
        imagePullPolicy: Never
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: http
          containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: assets-server
spec:
  selector:
    app: assets-server
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
