repos:
- repo: https://github.com/norwoodj/helm-docs
  rev: v1.2.0
  hooks:
  - id: helm-docs
    args:
    # Make the tool search for charts only under the `charts/node` directory.
    # Other charts do not support helm-docs for now
    - --chart-search-root=charts
    - --template-files=README.md.gotmpl
