{{- $fullName := include "testnet-manager.fullname" . -}}
# Create Role (doesn't grant permissions by itself)
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $fullName }}-pod-reader
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $fullName }}-configmap-reader
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $fullName }}-statefulset-reader
rules:
  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $fullName }}-volume-reader
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes", "persistentvolumeclaims"]
    verbs: ["get", "list"]
---
# Creat Role bindings
{{- $serviceAccountName := include "testnet-manager.serviceAccountName" . -}}
# Allow the testnet-manager service account to read pods in the current namespace
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ $fullName }}-read-pods
  namespace: {{ $.Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $fullName }}-pod-reader
subjects:
- kind: ServiceAccount
  name: {{ $serviceAccountName }}
  namespace: {{ $.Release.Namespace }}
---
# Allow the testnet-manager service account to read configmaps in the current namespace
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ $fullName }}-read-confimaps
  namespace: {{ $.Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $fullName }}-configmap-reader
subjects:
- kind: ServiceAccount
  name: {{ $serviceAccountName }}
  namespace: {{ $.Release.Namespace }}
---
# Allow the testnet-manager service account to read statefulsets in the current namespace
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ $fullName }}-read-statefulsets
  namespace: {{ $.Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $fullName }}-statefulset-reader
subjects:
  - kind: ServiceAccount
    name: {{ $serviceAccountName }}
    namespace: {{ $.Release.Namespace }}
---
# Allow the testnet-manager service account to read volumes in the current namespace
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ $fullName }}-read-volume
  namespace: {{ $.Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ $fullName }}-volume-reader
subjects:
  - kind: ServiceAccount
    name: {{ $serviceAccountName }}
    namespace: {{ $.Release.Namespace }}
---
# Allow the testnet-manager service account to read nodes of the pod in the current namespace
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ $fullName }}-read-node
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ $fullName }}-node-reader
subjects:
- kind: ServiceAccount
  name: {{ $serviceAccountName }}
  namespace: {{ $.Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ $fullName }}-read-node
  apiGroup: rbac.authorization.k8s.io
