node:
  chain: dev
  role: invalid
  flags:
  - "--force-authoring"
  - "--alice"
  chainData:
    storageClass: standard
    volumeSize: 1Gi
  chainKeystore:
    storageClass: standard
  podManagementPolicy: Parallel
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Delete
    whenScaled: Delete
  substrateApiSidecar:
    enabled: true
image:
  tag: v0.9.43
autoscaling:
  enabled: true
  targetCPU: 80
  targetMemory: 80
  maxReplicas: 2

substrateApiSidecar:
  metrics:
    enabled: true
