node:
  chain: dev
  role: invalid
  dataVolumeSize: 1G
  flags:
  - "--force-authoring"
  - "--alice"
  chainData:
    storageClass: standard
  chainKeystore:
    storageClass: standard
  podManagementPolicy: Parallel
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Delete
    whenScaled: Delete
image:
  tag: v0.9.43
