{{- if (.Values.bot.enabled) -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-bot
  labels:
    {{- include "faucet.botLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "faucet.botSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "faucet.botSelectorLabels" . | nindent 8 }}
      annotations:
        configmap/checksum: {{ include (print $.Template.BasePath "/bot-configmap.yaml") . | sha256sum }}
        secret/checksum: {{ include (print $.Template.BasePath "/bot-secret.yaml") . | sha256sum }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "faucet.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: faucet-bot
          image: "{{ .Values.bot.image.repository }}:{{ .Values.bot.image.tag }}"
          imagePullPolicy: {{ .Values.bot.image.pullPolicy }}
          env:
          {{- range $key, $val := .Values.bot.secret }}
            - name: {{ $key }}
              valueFrom:
                secretKeyRef:
                  key: {{ $key }}
                  name: {{ $.Values.bot.existingSecret | default (printf "%s-bot-secret" $.Release.Name) }}
          {{- end }}
          {{- range $key, $val := .Values.bot.config }}
            - name: {{ $key }}
              valueFrom:
                configMapKeyRef:
                  key: {{ $key }}
                  name: {{ $.Values.bot.existingConfigMap | default (printf "%s-bot-config" $.Release.Name) }}
          {{- end }}
            - name: SMF_BOT_BACKEND_URL
              value: "http://{{ .Release.Name }}-server:{{ .Values.server.config.SMF_BACKEND_PORT }}"
            - name: SMF_BOT_DEPLOYED_REF
              value: "{{ .Values.server.image.repository }}:{{ .Values.server.image.tag }}"
            - name: SMF_BOT_DEPLOYED_TIME
              value: {{ now | date "2006-01-02T15:04:05" | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}
