{{- if (not .Values.faucet.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
data:
  {{- range $key, $val := .Values.faucet.secret }}
  {{ $key }}: {{ $val | b64enc }}
  {{- end }}
{{- end }}
