apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "faucet.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 5555
      targetPort: 5555
      protocol: TCP
  selector:
    {{ include "faucet.selectorLabels" . | nindent 4 }}
