{{- if .Values.config }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "polkadot-basic-notification.fullname" . }}
  labels:
    {{- include "polkadot-basic-notification.labels" . | nindent 4 }}
data:
  {{- range $index := until (len .Values.config.configFiles ) }}
  configFile-{{ $index }}: {{ (index $.Values.config.configFiles $index) | quote }}
  {{- end }}
{{- end }}