{{- if (not .Values.config.secret.existingSecret) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "polkadot-basic-notification.fullname" . }}
  labels:
    {{- include "polkadot-basic-notification.labels" . | nindent 4 }}
type: Opaque
data:
  MATRIX_ACCESSTOKEN: {{ .Values.config.secret.MATRIX_ACCESSTOKEN | b64enc | quote }}
  MATRIX_USERID: {{ .Values.config.secret.MATRIX_USERID | b64enc | quote }}
{{- end }}
