{{- if .Values.serviceMonitor.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "polkadot-basic-notification.fullname" . }}
  namespace: {{ template "polkadot-basic-notification.namespace" . }}
  labels:
    {{- include "polkadot-basic-notification.labels" . | nindent 4 }}
  {{- if .Values.serviceMonitor.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  endpoints:
{{ toYaml .Values.serviceMonitor.endpoints | indent 4 }}
  jobLabel: "{{ .Release.Name }}"
  selector:
    matchLabels:
      {{- include "polkadot-basic-notification.selectorLabels" . | nindent 8 }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
{{- end }}
