apiVersion: v2
name: simple-relay-parachain
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
dependencies:
  - name: node
    version: "5.15.0"
    repository: "https://paritytech.github.io/helm-charts/"
