node:
  image:
    repository: parity/polkadot-parachain

  node:
    chain: asset-hub-rococo-local
    command: polkadot-parachain
    role: collator
    replicas: 2
    keys:
      # This is Alice seed. To generate new seed run: docker run --rm parity/polkadot:latest key generate
      - seed: "bottom drive obey lake curtain smoke basket hold race lonely fit walk"
        type: aura
        scheme: sr25519
        # ${HOSTNAME##*-} will be evaluated as the pod index, pod-0: //Alice, pod-1: //Bob
        extraDerivation: '$([ "${HOSTNAME##*-}" = "0" ] && echo "//Alice" || echo "//Bob")'
    customNodeKey:
     - "0000000000000000000000000000000000000000000000000000000000000004"
     - "0000000000000000000000000000000000000000000000000000000000000005"
    flags:
      # This corresponds to the generated node key
      - "--bootnodes /dns/parachain-node-0/tcp/30334/p2p/12D3KooWSsChzF81YDUKpe9Uk5AHV5oqAaXAcWNSPYgoLauUk4st"
    isParachain: true
    collatorRelayChain:
      chain: rococo-local
      customChainspecUrl: http://bootnode:8080/chainspec.json
      forceDownloadChainspec: true
      flags:
        - "--allow-private-ipv4"
        - "--discover-local"

  extraInitContainers:
    - name: dump-state-and-wasm
      image: "parity/polkadot-parachain:latest"
      securityContext:
        runAsUser: 0
      command: [ "/bin/bash" ]
      args:
        - -c
        - |
          if [ "${HOSTNAME##*-}" = "0" ]; then
            echo "Parachain Id:"
            {{ .Values.node.command }} build-spec --chain {{ .Values.node.chain }} | grep -E 'para_id|parachainId'
            echo "Genesis head:"
            {{ .Values.node.command }} export-genesis-state --chain {{ .Values.node.chain }}
            echo ""
            echo "Genesis wasm (validationCode) stored in /chain-data/genesis-wasm"
            {{ .Values.node.command }} export-genesis-wasm  --chain {{ .Values.node.chain }} > /chain-data/genesis-wasm
          else
           echo "Genesis head and wasm are in pod ${HOSTNAME%-*}-0"
          fi
      volumeMounts:
        - mountPath: /chain-data
          name: chain-data

