{{- if .Values.autoscaling.shard.enabled }}
{{- if semverCompare ">=1.23-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: autoscaling/v2
{{- else -}}
apiVersion: autoscaling/v2beta1
{{- end }}
kind: HorizontalPodAutoscaler
metadata:
  name: telemetry-shard
  labels:
    {{- include "substrate-telemetry.labels" . | nindent 4 }}
    telemetry-component: shard
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: telemetry-shard
  minReplicas: {{ .Values.autoscaling.shard.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.shard.maxReplicas }}
  metrics:
    {{- if .Values.autoscaling.shard.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .Values.autoscaling.shard.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.autoscaling.shard.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ .Values.autoscaling.shard.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
