apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nominimonitor.fullname" . }}
  labels:
    {{- include "nominimonitor.labels" . | nindent 4 }}
type: Opaque
data:
  MATRIX_ACCESSTOKEN: {{ .Values.nominimonitor.secret.MATRIX_ACCESSTOKEN | b64enc | quote }}
  MATRIX_USERID: {{ .Values.nominimonitor.secret.MATRIX_USERID | b64enc | quote }}
