{{ if .Values.googleCloudSdk.serviceAccountKey }}
{{ $fullname :=  include "node.fullname" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullname }}-gcs-bucket-service-account-key
data:
  service-account-key.json: {{ .Values.googleCloudSdk.serviceAccountKey }}
{{ end }}
