{{- if .Values.secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bridges-common-relay.fullname" . }}
  labels:
    {{- include "bridges-common-relay.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $key, $val := .Values.secrets }}
  {{ $key }}: {{ $val | b64enc }}
{{- end -}}
{{- end }}
