{{- if .Values.prometheus.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "bridges-common-relay.fullname" . }}
  labels:
    {{- include "bridges-common-relay.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: prometheus
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.prometheus.port }}
      protocol: TCP
  selector:
    {{- include "bridges-common-relay.selectorLabels" . | nindent 4 }}
{{- end }}
