{{- if and .Values.serviceMonitor.enabled .Values.prometheus.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "bridges-common-relay.fullname" . }}
  labels:
    {{- include "bridges-common-relay.labels" . | nindent 4 }}
  {{- if .Values.serviceMonitor.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  endpoints:
  - port: {{ .Values.service.portName }}
    {{- with .Values.serviceMonitor.interval }}
    interval: {{ . }}
    {{- end }}
    {{- with .Values.serviceMonitor.scrapeTimeout }}
    scrapeTimeout: {{ . }}
    {{- end }}
    honorLabels: true
    path: /metrics
    scheme: http
  {{- with .Values.serviceMonitor.targetLabels }}
  targetLabels:
  {{ toYaml .| nindent 6 }}
  {{- end}}
  jobLabel: "{{ .Release.Name }}"
  selector:
    matchLabels:
      {{- include "bridges-common-relay.selectorLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
{{- end }}
