{{- if .Values.config }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "polkadot-notification-service.fullname" . }}
  labels:
    {{- include "polkadot-notification-service.labels" . | nindent 4 }}
data:
  configFile: {{ .Values.config.configFile | quote }}
{{- end }}